# Generated by Django 4.1.5 on 2023-01-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingsofbook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='booklist/images'),
        ),
    ]
